# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Login' do
  before(:each) do
    options = Selenium::WebDriver::Options.chrome
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--proxy-server=zap:8090')
    options.add_argument('--ignore-certificate-errors')
    @driver = Selenium::WebDriver.for :chrome, options: options
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'login' do
    @driver.get('http://juice_shop:3000/#/login')
    @driver.find_element(:id, 'email').send_keys('user@mail.test')
    @driver.find_element(:id, 'password').send_keys('securepw')
    element = @driver.find_element(:css, '#loginButton .mat-icon')
    print("--- USER login ---\n")
    @driver.execute_script("arguments[0].click();", element)
    element = @driver.find_element(:id, 'navbarAccount')
    @driver.execute_script("arguments[0].click();", element)
    element = @driver.find_element(:css, '.cdk-focused > span')
    @driver.execute_script("arguments[0].click();", element)
    print("--- USER visited profile ---\n")
  end
end
