#load docker image & start docker engine
image: docker:20.10.16
services:
 - docker:20.10.16-dind

#variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - test
  - evaluate

wasttesting:
  tags:
    - ci-sec
  stage: test
  image: docker/compose
  allow_failure: true
  script:  
    - cd wasttesting
    - chmod o+w scanresults
    - ls -l
    - docker-compose up --exit-code-from zap_scan 2> docker-logs.txt
  after_script:
    - ls -l
    - exitcode=$(tail -n 1 docker-logs.txt)
    - case $var in \
        0) echo "Success";; \
        1) echo "At Least 1 FAIL";; \
        2) echo "At Least one WARN and no FAILS";; \
        3) echo "Any other failure";; \
      esac
  artifacts:
    name: wastreport
    when: always
    paths:
      - wasttesting/scanresults

# BUILD WAST
# build_wast_zap_script:
#   stage: build
#   before_script:
#     - cd wasttesting
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#   script:
#     - docker build pentest -t $CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-script-$CI_COMMIT_SHA
#     - docker push $CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-script-$CI_COMMIT_SHA

# build_wast_zap:
#   stage: build
#   before_script:
#     - cd wasttesting
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#   script:
#     - docker build zap -t $CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-$CI_COMMIT_SHA
#     - docker push $CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-$CI_COMMIT_SHA

# TEST WAST
# test_wast:
#   stage: test
#   image:
#     name: docker/compose
#   before_script:
#     # - apk add python3 zip
#     # - export ZAP_URL=$CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-$CI_COMMIT_SHA
#     # - export ZAP_SCRIPT_URL=$CI_REGISTRY/$CI_PROJECT_PATH:wast-zap-script-$CI_COMMIT_SHA
#     # - python3 update-compose.py --file='wasttesting/docker-compose.yaml' --variables 'zap_script_url' 'zap_url'
#     - cd wasttesting
#   script:
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker-compose up --abort-on-container-exit
#   artifacts:
#     paths:
#       - wasttesting/results
#     expire_in: 1 week

# # EVALUATE_WAST
# evaluate_wast:
#   stage: evaluate
#   before_script:
#     - apk add python3
#   script:
#     - python3 should_it_fail.py --file=wasttesting/results/zap/json/results.JSON
#   dependencies:
#     - test_wast
