version: '3'
services:
  zap_script:
    depends_on:
      - zap
      - juice_shop
    build: pentest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./results:/results/
  zap:
    build: zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
  juice_shop:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
