version: '3'
services:
  zap:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    volumes:
      - ./results:/home/zap/results

  jmeter:
    build: jmeter
    volumes:
      - ./results:/app/zapresults
    depends_on:
      - juice_shop
      - zap

  juice_shop:
    image: bkimminich/juice-shop
