version: '3'
services:
  juice_shop:
    image: bkimminich/juice-shop
  zap_scan:
    depends_on:
      - juice_shop
    image: owasp/zap2docker-stable
    command: zap-baseline.py -t http://juice_shop:3000 -d -r report.html
    volumes:
      - ./scanresults:/zap/wrk
